version: "3.7"
services:
  redis:
    image: redis:7.0.5-alpine
    command: redis-server --port 6379
    container_name: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    networks:
      - default
      - proxynet

networks:
  proxynet:
    name: lemmon-net
